### ISSUE TITLE
Notification showing multiple times

### ISSUE THREAD

**Issue by diivyu** [prscX/react-native-notification-banner#16]
When a notification is received in the foreground, it's rendering 3-4 times for a single notification.

Here is my code, please have a look :

```

  RNNotificationBanner.Show({
                        title: title && title != '' ? title : '',
                        subTitle: body && body != '' ? body : '',
                        tintColor: '#406FCA', onClick: this.onClickNotificationBanner.bind(this, notification)
                    })

```

**Comment by prscX** [comment]
@diivyu: Could you share the software stack, please.

I believe, the Show API must be getting called multiple times, otherwise it should not happen.

Thanks
</ Pranav >

**Comment by Ritesh175862** [comment]
> @diivyu: Could you share the software stack, please.
> 
> I believe, the Show API must be getting called multiple times, otherwise it should not happen.
> 
> Thanks
> </ Pranav >
can you provide any solution
