### ISSUE TITLE
How to use an image instead of an icon?

### ISSUE THREAD

**Issue by ghiteze** [prscX/react-native-notification-banner#3]

**Comment by ghiteze** [comment]
Maybe I should change generateVectorIcon func

**Comment by prscX** [comment]
Thanks @ghiteze for raising the query.

Please refer below `README` reference for using the vector icons:

[icons](https://github.com/prscX/react-native-notification-banner#icons)

Please let me know in case you face any issues.

Thanks
</ Pranav >
