### ISSUE TITLE
Pods.xcodeproj is not found

### ISSUE THREAD

**Issue by AdamLee321** [prscX/react-native-notification-banner#5]
I have added the library to my app and followed the installation instructions, but I can't find the Pods.xcodeproj. Everything else is there but this.

Has anyone had this issue?

**Comment by prscX** [comment]
Thanks @AdamLee321 for raising the issue.

Please find below screenshot of `node_module` folder looks like when I do a installation. Could you please share your project structure in order resolve the issue.

<img width="825" alt="screenshot 2019-03-03 at 8 57 21 pm" src="https://user-images.githubusercontent.com/28862892/53697450-3829f100-3df7-11e9-9b3c-d09e7b455003.png">

Thanks
</ Pranav >

**Comment by AdamLee321** [comment]
Hi, thanks for your response on this issue. 

I have attached what is in my folder after I install the library. If hope this is what you need to resolve this issue.

<img width="720" alt="screenshot 2019-03-04 at 09 16 12" src="https://user-images.githubusercontent.com/22890658/53722807-3e06ed00-3e5e-11e9-90d8-fb50e351966c.png">

Thanks, Adam.

**Comment by AdamLee321** [comment]
I have tested this on my mac and two others, only 1 out of 3 installed the Pods.xcodeproj. And this Mac was the oldest of the 3. Hope this helps.

**Comment by prscX** [comment]
Hi: Do you have cocoapods install on your system?

Thanks
</ Pranav >

**Comment by AdamLee321** [comment]
Yeah, I am currently investigating that route as My version of cocoapods is 1.6.1.beta.1, so I am upgrading to a stable version 1.6.1. And I will see if this fixes my problem.

**Comment by AdamLee321** [comment]
Upgrading to 1.6.1 has not fixed the issue, do you know what version you are on? I will downgrade and test...

**Comment by prscX** [comment]
@AdamLee321: Mine is 1.5.3. could you please try this once.

Thanks
</ Pranav >

**Comment by AdamLee321** [comment]
Hello Pranav, 

I have downgraded to version 1.5.3 and the Pods.xcodeproj has installed successfully.

<img width="1187" alt="screenshot 2019-03-06 at 09 02 36" src="https://user-images.githubusercontent.com/22890658/53868741-9cfb6c00-3fee-11e9-9443-058b2b93c989.png">

I'm sure how you can go about fixing this issue. At least you are aware that newer versions of cocoapods do not work with your library in its current state.

Also I'm not sure if it is something you should add to the readme for your library, but your library is fully compatible with wix/react-native-navigation, and seems to be the only one, except for wix's on library which is a nuisance to install.

Thanks for a nice simple library, and thanks for your help.

**Comment by prscX** [comment]
Thanks @AdamLee321 for sharing your findings.

I will definitely look into the cocoapods version issue.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi All: I have pushed the release with the cocoapods installation issue.

Could you please install latest release and verify the same. Please let me know if you still face the same issue.

Thanks
</ Pranav >
