### ISSUE TITLE
iOS installation

### ISSUE THREAD

**Issue by ejkkan** [prscX/react-native-notification-banner#6]
I have not had any luck implementing either this lib, or your https://github.com/prscX/react-native-fluidic-slider lib, with ios. They use kind of the same installation pattern.

Is there a reason for the setup using this specific pattern, or would it be possible to install them the way most libs do. I.e adding needed pods to to the project own podfile and os on.

Also BRYXbanner throws this error for me:
BRYXBanner` does not specify a Swift version and none of the targets (`...`) integrating it have the `SWIFT_VERSION` attribute set.

How did you get around it?

**Comment by barclayd** [comment]
As explained in this Issue https://github.com/prscX/react-native-notification-banner/issues/5, there's currently an issue with the repo that means that the Pods.xcodeproj cannot be installed in a version of cocoapods greater than 1.5.3

How to downgrade to 1.5.3:

```sudo gem uninstall cocoapods```
```sudo gem install cocoapods -v 1.5.3```

If you now run ```pod install``` whilst inside directory  ```~/Documents/Coding/drinks-app/mobile/node_modules/react-native-notification-banner/ios``` you should be able to see that Pods.xcodeproj is downloaded and you can continue with the installation 😊

**Comment by ejkkan** [comment]
Wow, i tried just installing cocoapods 1.5.3 and use that setup. 
uninstall and then install solved it! Thanks!

**Comment by prscX** [comment]
Hi: I have found the fix. I will push the release.

Basically, based on latest pods, the native library should define swift version which was earlier not needed. 

Thanks
</ Pranav >

**Comment by barclayd** [comment]
Thank you for all of the wonderful work on this library, it’s been a fantastic addition to my current React Native project!

That’s excellent news, many thanks Pranav!

**Comment by prscX** [comment]
Hi All: I have pushed the release with the cocoapods installation issue.

Could you please install latest release and verify the same. Please let me know if you still face the same issue.

Thanks
</ Pranav >
